// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"database/sql"
	"fmt"

	"pi-webpage/db"
)

func formatNullFloat(v sql.NullFloat64, format string) string {
	if !v.Valid {
		return "—"
	}
	return fmt.Sprintf(format, v.Float64)
}

type BodyPageModel struct {
	Today    string
	History  []db.BodyMetric
	ErrorMsg string
	OkMsg    string
	HasDOB   bool
}

func BodyPage(m BodyPageModel) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"page-header\"><div><div class=\"metric-label\">body metrics</div><div class=\"metric-sub\">weight &middot; body fat %</div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if m.OkMsg != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"form-ok\">&#10003; saved</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if m.ErrorMsg != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"form-err\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(m.ErrorMsg)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/body.templ`, Line: 38, Col: 37}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !m.HasDOB {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<div class=\"form-warn\">USER_DOB not set in .env — BF% won't be computed until you add it (format YYYY-MM-DD).</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, " <div class=\"body-forms\"><form class=\"body-form\" method=\"POST\" action=\"/body\"><div class=\"form-title\">LOG WEIGHT</div><div class=\"body-row\"><label class=\"body-field\"><span class=\"metric-label\">DATE</span> <input type=\"date\" name=\"date\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(m.Today)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/body.templ`, Line: 52, Col: 52}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\" class=\"body-input\" required></label> <label class=\"body-field\"><span class=\"metric-label\">WEIGHT (LBS)</span> <input type=\"number\" step=\"0.1\" min=\"0\" name=\"weight_lbs\" placeholder=\"170.5\" class=\"body-input\" required></label></div><div style=\"margin-top: 1rem;\"><button type=\"submit\" class=\"btn-terminal\">save weight</button></div></form><form class=\"body-form\" method=\"POST\" action=\"/body\"><div class=\"form-title\">LOG BODY FAT</div><div class=\"body-row\"><label class=\"body-field\"><span class=\"metric-label\">DATE</span> <input type=\"date\" name=\"date\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(m.Today)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/body.templ`, Line: 69, Col: 52}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\" class=\"body-input\" required></label></div><div class=\"body-row\" style=\"margin-top: 0.5rem;\"><label class=\"body-field\"><span class=\"metric-label\">CHEST (MM)</span> <input type=\"number\" step=\"0.1\" min=\"0\" name=\"chest_mm\" placeholder=\"12.5\" class=\"body-input\" required></label> <label class=\"body-field\"><span class=\"metric-label\">ABDOMEN (MM)</span> <input type=\"number\" step=\"0.1\" min=\"0\" name=\"abdomen_mm\" placeholder=\"18.0\" class=\"body-input\" required></label> <label class=\"body-field\"><span class=\"metric-label\">THIGH (MM)</span> <input type=\"number\" step=\"0.1\" min=\"0\" name=\"thigh_mm\" placeholder=\"14.0\" class=\"body-input\" required></label></div><div style=\"margin-top: 1rem;\"><button type=\"submit\" class=\"btn-terminal\">save body fat</button> <span class=\"metric-sub\" style=\"margin-left: 0.75rem;\">BF% auto-computed (Jackson-Pollock)</span></div></form></div><div class=\"metric-label\" style=\"margin: 1.5rem 0 0.5rem;\">HISTORY</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if len(m.History) == 0 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<div class=\"detail-empty\">no entries yet</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<div class=\"runs-table\"><table><thead><tr><th>DATE</th><th>WEIGHT</th><th>BF %</th><th>CHEST</th><th>ABDOMEN</th><th>THIGH</th></tr></thead> <tbody>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				for _, b := range m.History {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<tr><td>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var6 string
					templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(b.Date)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/body.templ`, Line: 112, Col: 20}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</td><td class=\"weight-color\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var7 string
					templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(formatNullFloat(b.WeightLbs, "%.1f lb"))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/body.templ`, Line: 113, Col: 74}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</td><td class=\"bf-color\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var8 string
					templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(formatNullFloat(b.BfPercent, "%.1f%%"))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/body.templ`, Line: 114, Col: 69}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</td><td>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var9 string
					templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(formatNullFloat(b.ChestMm, "%.1f"))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/body.templ`, Line: 115, Col: 48}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "</td><td>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var10 string
					templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(formatNullFloat(b.AbdomenMm, "%.1f"))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/body.templ`, Line: 116, Col: 50}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "</td><td>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var11 string
					templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(formatNullFloat(b.ThighMm, "%.1f"))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/body.templ`, Line: 117, Col: 48}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "</td></tr>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "</tbody></table></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, " <style>\n\t\t\t.form-ok { color: var(--green); background: var(--green-faint); border: 1px solid var(--green-dim);\n\t\t\t\tpadding: 0.4rem 0.75rem; border-radius: 4px; font-size: 0.75rem; margin-bottom: 1rem; letter-spacing: 0.1em; }\n\t\t\t.form-err { color: #ff7766; background: rgba(255,80,80,0.08); border: 1px solid rgba(255,80,80,0.4);\n\t\t\t\tpadding: 0.4rem 0.75rem; border-radius: 4px; font-size: 0.75rem; margin-bottom: 1rem; letter-spacing: 0.05em; }\n\t\t\t.form-warn { color: #ffaa00; background: rgba(255,170,0,0.08); border: 1px solid rgba(255,170,0,0.4);\n\t\t\t\tpadding: 0.4rem 0.75rem; border-radius: 4px; font-size: 0.7rem; margin-bottom: 1rem; }\n\n\t\t\t.body-forms {\n\t\t\t\tdisplay:grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));\n\t\t\t\tgap: 0.75rem;\n\t\t\t}\n\t\t\t.body-form {\n\t\t\t\tbackground: var(--bg2); border: 1px solid var(--border);\n\t\t\t\tborder-radius: 6px; padding: 1.25rem;\n\t\t\t}\n\t\t\t.form-title {\n\t\t\t\tfont-size: 0.65rem; letter-spacing: 0.2em;\n\t\t\t\tcolor: var(--green); margin-bottom: 0.75rem;\n\t\t\t\tpadding-bottom: 0.5rem; border-bottom: 1px solid var(--border);\n\t\t\t}\n\t\t\t.body-row {\n\t\t\t\tdisplay:grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));\n\t\t\t\tgap: 0.75rem;\n\t\t\t}\n\t\t\t.body-field { display: flex; flex-direction: column; gap: 0.3rem; }\n\t\t\t.body-input {\n\t\t\t\tbackground: rgba(0,255,136,0.04);\n\t\t\t\tborder: 1px solid var(--border); border-radius: 4px;\n\t\t\t\tcolor: var(--green); font-family: inherit;\n\t\t\t\tfont-size: 0.85rem; padding: 0.5rem 0.6rem;\n\t\t\t\toutline: none; transition: border-color 0.15s;\n\t\t\t}\n\t\t\t.body-input:focus {\n\t\t\t\tborder-color: var(--green-dim);\n\t\t\t\tbox-shadow: 0 0 8px rgba(0,255,136,0.15);\n\t\t\t}\n\t\t\t.weight-color { color: #5ce1e6 !important; }\n\t\t\t.bf-color { color: #ff70b3 !important; }\n\t\t</style>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("body").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
