// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" data-theme=\"forest\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/layout.templ`, Line: 9, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " | pi</title><link href=\"https://cdn.jsdelivr.net/npm/daisyui@5/dist/full.min.css\" rel=\"stylesheet\"><script src=\"https://cdn.tailwindcss.com\"></script><script src=\"https://unpkg.com/htmx.org@2.0.4\"></script><script src=\"https://unpkg.com/hyperscript.org@0.9.14\"></script><style>\n\t\t\t\tbody { font-family: 'Courier New', monospace; }\n\t\t\t\t.metric-label { letter-spacing: 0.1em; text-transform: uppercase; font-size: 0.7rem; }\n\t\t\t</style></head><body class=\"min-h-screen bg-base-300\"><div class=\"navbar bg-base-100 border-b border-base-content/10 px-6\"><div class=\"flex-1\"><span class=\"text-primary font-bold text-lg tracking-widest\">[ PI ]</span></div><nav class=\"flex gap-2 items-center\"><a href=\"/\" class=\"btn btn-ghost btn-sm font-mono\">stats</a> <a href=\"/health\" class=\"btn btn-ghost btn-sm font-mono opacity-40 cursor-not-allowed\" title=\"coming soon\">health</a> <a href=\"/calories\" class=\"btn btn-ghost btn-sm font-mono opacity-40 cursor-not-allowed\" title=\"coming soon\">calories</a> <a href=\"/workouts\" class=\"btn btn-ghost btn-sm font-mono opacity-40 cursor-not-allowed\" title=\"coming soon\">workouts</a><div class=\"w-px h-4 bg-base-content/20 mx-1\"></div><form method=\"POST\" action=\"/logout\"><button type=\"submit\" class=\"btn btn-ghost btn-sm font-mono text-base-content/40 hover:text-error\">logout</button></form></nav></div><main class=\"p-6 max-w-5xl mx-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
